#!/usr/bin/bash
source "$HOME/Defaults" || exit 1

sudo "${CE_EXEC}" login -u "${REPOUSER}" -p "${REPOPASS}" "${ENDPOINT}" &>/dev/null

sudo podman commit -a "HyperSpire Foundation" -p -f docker mysql-server "${REPO}/oracle/mysql-server:latest"
