#!/usr/bin/bash
source "$HOME/Defaults" || exit 1

sudo "${CE_EXEC}" login -u "${REPOUSER}" -p "${REPOPASS}" "${ENDPOINT}" &>/dev/null

sudo podman create --cap-add SYS_NICE,SYS_RESOURCE,NET_ADMIN,AUDIT_WRITE -i -t -m 4g --memory-reservation 2g --memory-swap 4g -p 3306 --name mysql-server --replace container-registry.oracle.com/os/oraclelinux:8-slim

sudo podman commit -f docker -a "HyperSpire Foundation" mysql-server "${REPO}/oracle/mysql:latest"
