apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql-server
  name: mysql-server
  namespace: default
spec:
  containers:
    - image: phx.ocir.io/axmvl4uui9gb/oracle/mysql-server:latest
      imagePullPolicy: Never
      name: mysql-server
      ports:
        - containerPort: 22
          protocol: TCP
          name: opensshd
        - containerPort: 3306
          protocol: TCP
          name: mysql
        - containerPort: 33060
          protocol: TCP
          name: mysqlx
        - containerPort: 33061
          protocol: TCP
          name: mysql-group
      resources:
        requests:
          memory: "2G"
          cpu: "250m"
        limits:
          memory: "4G"
          cpu: "500m"
      securityContext:
        capabilities:
          add:
            - SYS_NICE
            - SYS_RESOURCE
            - NET_ADMIN
            - AUDIT_WRITE
  restartPolicy: Always
  nodeName: 10.10.110.115
